/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of user Organizations */
        get: operations["getOrganizations"];
        put?: never;
        /** Create new Organization */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Organization by ID */
        get: operations["getOrganizationById"];
        /** Update Organization */
        put: operations["updateOrganization"];
        post?: never;
        /** Delete Organization */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Organization Units */
        get: operations["getOrganizationUnits"];
        put?: never;
        /** Create Organization Unit */
        post: operations["createUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Unit by ID */
        get: operations["getOrganizationUnitById"];
        /** Update Organization Unit */
        put: operations["updateOrganizationUnit"];
        post?: never;
        /** Delete Organization Unit */
        delete: operations["deleteOrganizationUnit"];
        options?: never;
        head?: never;
        /** Patch Organization Unit */
        patch: operations["patchOrganizationUnit"];
        trace?: never;
    };
    "/storage-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Storage Groups */
        get: operations["getStorageGroups"];
        put?: never;
        /** Create Storage Group */
        post: operations["createStorageGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Storage Group by ID */
        get: operations["getStorageGroupById"];
        /** Update Storage Group */
        put: operations["updateStorageGroup"];
        post?: never;
        /** Delete Storage Group */
        delete: operations["deleteStorageGroup"];
        options?: never;
        head?: never;
        /** Patch Storage Group */
        patch: operations["patchStorageGroup"];
        trace?: never;
    };
    "/cells-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Cells Groups */
        get: operations["getCellsGroups"];
        put?: never;
        /** Create Cells Group */
        post: operations["createCellsGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cells-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cells Group ID */
                groupId: string;
            };
            cookie?: never;
        };
        /** Get Cells Group by ID */
        get: operations["getCellsGroupById"];
        /** Update Cells Group */
        put: operations["updateCellsGroup"];
        post?: never;
        /** Delete Cells Group */
        delete: operations["deleteCellsGroup"];
        options?: never;
        head?: never;
        /** Patch Cells Group */
        patch: operations["patchCellsGroup"];
        trace?: never;
    };
    "/cells-groups/{groupId}/cells": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        /** Get list of Cells */
        get: operations["getCells"];
        put?: never;
        /** Create Cells */
        post: operations["createCell"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cells-groups/{groupId}/cells/{cellId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                cellId: string;
            };
            cookie?: never;
        };
        /** Get Cell by ID */
        get: operations["getCellById"];
        /** Update Cell */
        put: operations["updateCell"];
        post?: never;
        /** Delete Cell */
        delete: operations["deleteCell"];
        options?: never;
        head?: never;
        /** Patch Cell */
        patch: operations["patchCell"];
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Items */
        get: operations["getItems"];
        put?: never;
        /** Create Item */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Item by ID */
        get: operations["getItemById"];
        /** Update Item */
        put: operations["updateItem"];
        post?: never;
        /** Delete Item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        /** Patch Item */
        patch: operations["patchItem"];
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Instances */
        get: operations["getInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{itemId}/instances": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                itemId: string;
            };
            cookie?: never;
        };
        /** Get list of Instances For Item */
        get: operations["getInstancesByItemId"];
        put?: never;
        /** Create Instance For Item */
        post: operations["createInstanceForItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Instance ID */
                instanceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Instance by ID */
        delete: operations["deleteInstanceById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Service API Tokens */
        get: operations["getApiTokens"];
        put?: never;
        /** Create Service API Token */
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Service API Token */
        delete: operations["revokeApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth2/yandex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Yandex Access token for Session token */
        post: operations["exchangeYandexAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout user */
        get: operations["logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["getCurrentUser"];
        /** Update Current User */
        put: operations["putCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Current User */
        patch: operations["patchCurrentUser"];
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get employees of the organization
         * @description Get all employees
         */
        get: operations["getEmployees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get employee by id */
        get: operations["getEmployeeById"];
        put?: never;
        post?: never;
        /** Delete employee by id */
        delete: operations["deleteEmployeeById"];
        options?: never;
        head?: never;
        /** Update employee by id */
        patch: operations["patchEmployeeById"];
        trace?: never;
    };
    "/employees/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite employee to the organization
         * @description Invite employee to the organization
         */
        post: operations["inviteEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all roles in system */
        get: operations["getRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get audit logs
         * @description Get audit logs
         */
        get: operations["getAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorContent: {
            error: {
                code: string;
                message: string;
            };
        };
        OrganizationBase: {
            /** @example Exotic */
            name: string;
            /** @example exotic */
            subdomain: string;
        };
        Organization: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            readonly id: string;
        } & components["schemas"]["OrganizationBase"];
        GetOrganizationsResponse: {
            data: components["schemas"]["Organization"][];
        };
        CreateOrganizationRequest: components["schemas"]["OrganizationBase"];
        CreateOrganizationResponse: {
            data: components["schemas"]["Organization"];
        };
        GetOrganizationByIdResponse: {
            data: components["schemas"]["Organization"];
        };
        OrganizationUpdate: {
            /** @example Exotic */
            name: string;
        };
        UpdateOrganizationRequest: components["schemas"]["OrganizationUpdate"];
        UpdateOrganizationResponse: {
            data: components["schemas"]["Organization"];
        };
        /** @example A1 */
        "storage-alias": string;
        UnitBase: {
            /** @example Moscow */
            name: string;
            alias: components["schemas"]["storage-alias"];
            /** @example 123 Main St, Moscow, Russia */
            address?: string | null;
        };
        Unit: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            readonly id: string;
        } & components["schemas"]["UnitBase"] & {
            address: string | null;
        };
        GetOrganizationUnitsResponse: {
            data: components["schemas"]["Unit"][];
        };
        CreateOrganizationUnitRequest: components["schemas"]["UnitBase"];
        CreateOrganizationUnitResponse: {
            data: components["schemas"]["Unit"];
        };
        GetOrganizationUnitByIdResponse: {
            data: components["schemas"]["Unit"];
        };
        UpdateOrganizationUnitRequest: components["schemas"]["UnitBase"];
        UpdateOrganizationUnitResponse: {
            data: components["schemas"]["Unit"];
        };
        UnitPatch: {
            /** @example Moscow */
            name?: string;
            /** @example MWS */
            alias?: string;
            address?: string | null;
        };
        PatchOrganizationUnitRequest: components["schemas"]["UnitPatch"];
        PatchOrganizationUnitResponse: {
            data: components["schemas"]["Unit"];
        };
        StorageGroupBase: {
            /** Format: uuid */
            parentId?: string | null;
            /** @example Main Warehouse */
            name: string;
            alias: components["schemas"]["storage-alias"];
            /** Format: uuid */
            unitId: string;
        };
        StorageGroup: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            parentId: string | null;
            /** Format: uuid */
            unitId: string;
        } & components["schemas"]["StorageGroupBase"];
        GetStorageGroupsResponse: {
            data: components["schemas"]["StorageGroup"][];
        };
        CreateStorageGroupRequest: components["schemas"]["StorageGroupBase"];
        CreateStorageGroupResponse: {
            data: components["schemas"]["StorageGroup"];
        };
        GetStorageGroupByIdResponse: {
            data: components["schemas"]["StorageGroup"];
        };
        UpdateStorageGroupRequest: components["schemas"]["StorageGroupBase"];
        UpdateStorageGroupResponse: {
            data: components["schemas"]["StorageGroup"];
        };
        StorageGroupPatch: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            parentId?: string | null;
            /** @example Main Warehouse */
            name?: string;
            /** @example MW */
            alias?: string;
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            unitId?: string;
        };
        PatchStorageGroupRequest: components["schemas"]["StorageGroupPatch"];
        PatchStorageGroupResponse: {
            data: components["schemas"]["StorageGroup"];
        };
        CellGroupBase: {
            name: string;
            alias: components["schemas"]["storage-alias"];
            /** Format: uuid */
            storageGroupId?: string | null;
            /** Format: uuid */
            unitId: string;
        };
        CellGroup: {
            /** Format: uuid */
            readonly id: string;
        } & components["schemas"]["CellGroupBase"] & {
            /** Format: uuid */
            unitId: string;
            /** Format: uuid */
            storageGroupId: string | null;
        };
        GetCellsGroupsResponse: {
            data: components["schemas"]["CellGroup"][];
        };
        CreateCellsGroupRequest: components["schemas"]["CellGroupBase"];
        CreateCellsGroupResponse: {
            data: components["schemas"]["CellGroup"];
        };
        GetCellsGroupByIdResponse: {
            data: components["schemas"]["CellGroup"];
        };
        UpdateCellsGroupRequest: components["schemas"]["CellGroupBase"];
        UpdateCellsGroupResponse: {
            data: components["schemas"]["CellGroup"];
        };
        CellGroupPatch: {
            name?: string;
            alias?: components["schemas"]["storage-alias"];
            /** Format: uuid */
            storageGroupId?: string;
            /** Format: uuid */
            unitId?: string;
        };
        PatchCellsGroupRequest: components["schemas"]["CellGroupPatch"];
        PatchCellsGroupResponse: {
            data: components["schemas"]["CellGroup"];
        };
        CellBase: {
            /** Format: uuid */
            readonly id: string;
            alias: string;
            row: number;
            level: number;
            position: number;
        };
        GetCellsResponse: {
            data: components["schemas"]["CellBase"][];
        };
        CreateCellRequest: components["schemas"]["CellBase"];
        CreateCellResponse: {
            data: components["schemas"]["CellBase"];
        };
        GetCellByIdResponse: components["schemas"]["CellBase"];
        UpdateCellRequest: components["schemas"]["CellBase"];
        UpdateCellResponse: {
            data: components["schemas"]["CellBase"];
        };
        CellPatch: {
            alias?: string;
            row?: number;
            level?: number;
            position?: number;
        };
        PatchCellRequest: components["schemas"]["CellPatch"];
        PatchCellResponse: {
            data: components["schemas"]["CellBase"];
        };
        ItemBase: {
            /** Format: uuid */
            readonly id?: string;
            /** @example Item 1 */
            name: string;
            /** @example Description */
            description?: string | null;
        };
        Item: components["schemas"]["ItemBase"] & {
            /** Format: uuid */
            readonly id: string;
            description: string | null;
        };
        ItemVariantBase: {
            /** @example Variant 1 */
            name: string;
            /** @example 123456789012 */
            article?: string | null;
            /** @example 1234567890123 */
            ean13?: number | null;
        };
        ItemVariant: {
            /** Format: uuid */
            readonly id: string;
        } & components["schemas"]["ItemVariantBase"] & {
            /** @example 123456789012 */
            article: string | null;
            /** @example 1234567890123 */
            ean13: number | null;
        };
        ItemForList: components["schemas"]["Item"] & {
            variants: components["schemas"]["ItemVariant"][];
        };
        GetItemsResponse: {
            data: components["schemas"]["ItemForList"][];
        };
        ItemCreate: components["schemas"]["ItemBase"] & {
            variants: components["schemas"]["ItemVariantBase"][];
        };
        CreateItemRequest: components["schemas"]["ItemCreate"];
        CellForInstance: components["schemas"]["CellBase"] & {
            cellPath: {
                /** Format: uuid */
                id: string;
                name: string;
                alias: string;
                /** @enum {string} */
                objectType: "cell" | "cells_group" | "storage_group";
            }[];
        };
        InstanceForItem: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "available" | "reserved" | "consumed";
            variant: components["schemas"]["ItemVariant"];
            cell: components["schemas"]["CellForInstance"];
        };
        ItemFull: components["schemas"]["Item"] & {
            variants: components["schemas"]["ItemVariant"][];
            instances: components["schemas"]["InstanceForItem"][];
        };
        CreateItemResponse: {
            data: components["schemas"]["ItemFull"];
        };
        GetItemByIdResponse: {
            data: components["schemas"]["ItemFull"];
        };
        ItemVariantEdit: {
            /** Format: uuid */
            id: string;
        } & components["schemas"]["ItemVariantBase"];
        UpdateItemRequest: components["schemas"]["ItemCreate"] & {
            variants?: components["schemas"]["ItemVariantEdit"][];
        };
        UpdateItemResponse: {
            data: components["schemas"]["ItemFull"];
        };
        ItemVariantPatchInItem: {
            /** Format: uuid */
            id?: string;
            /** @example Variant 1 */
            name?: string;
            /** @example 123456789012 */
            article?: string | null;
            /** @example 1234567890123 */
            ean13?: number | null;
        };
        ItemPatch: {
            /** @example Item 1 */
            name?: string;
            /** @example Description */
            description?: string | null;
            variants?: components["schemas"]["ItemVariantPatchInItem"][];
        };
        PatchItemRequest: components["schemas"]["ItemPatch"];
        PatchItemResponse: {
            data: components["schemas"]["ItemFull"];
        };
        InstanceFull: {
            /**
             * Format: uuid
             * @description Instance ID
             */
            readonly id: string;
            /** @enum {string} */
            status: "available" | "reserved" | "consumed";
            item?: components["schemas"]["Item"];
            variant: components["schemas"]["ItemVariant"];
            cell: components["schemas"]["CellForInstance"];
        };
        GetInstancesResponse: {
            data: components["schemas"]["InstanceFull"][];
        };
        GetInstancesByItemIdResponse: {
            data: components["schemas"]["InstanceForItem"][];
        };
        InstanceCreateForItem: {
            /** Format: uuid */
            variantId: string;
            /** Format: uuid */
            cellId?: string | null;
        };
        CreateInstanceForItemRequest: components["schemas"]["InstanceCreateForItem"];
        CreateInstanceForItemResponse: {
            data: components["schemas"]["InstanceForItem"][];
        };
        Token: {
            /** Format: uuid */
            readonly id: string;
            /** @description The name of the token */
            name: string;
            /** @description The token secret */
            token: string;
        };
        GetApiTokensResponse: {
            data: components["schemas"]["Token"][];
        };
        TokenCreate: {
            /** @description The name of the token */
            name: string;
        };
        CreateApiTokenRequest: components["schemas"]["TokenCreate"];
        CreateApiTokenResponse: {
            data: components["schemas"]["Token"];
        };
        User: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            middle_name: string | null;
            email: string;
        };
        GetCurrentUserResponse: components["schemas"]["User"];
        UserUpdate: {
            first_name: string;
            last_name: string;
            middle_name: string | null;
        };
        UpdateCurrentUserRequest: components["schemas"]["UserUpdate"];
        UserPatch: {
            first_name: string;
            last_name: string;
            middle_name: string | null;
        };
        PatchCurrentUserRequest: components["schemas"]["UserPatch"];
        Role: {
            id: number;
            name: string;
            displayName: string;
            description: string;
        };
        Employee: {
            /** Format: uuid */
            userId: string;
            firstName: string;
            lastName: string;
            middleName: string | null;
            email: string;
            role: components["schemas"]["Role"];
        };
        GetEmployeesResponse: {
            data: components["schemas"]["Employee"][];
        };
        GetEmployeeResponse: {
            data: components["schemas"]["Employee"];
        };
        PatchEmployeeRequest: {
            /** Format: uuid */
            userId: string;
            roleId?: number;
        };
        InviteEmployeeRequest: {
            email: string;
            roleId: number;
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            employee: components["schemas"]["Employee"];
            /** @enum {string} */
            action: "create" | "update" | "delete";
            /** Format: date-time */
            time: string;
            targetObjectType: {
                id: number;
                group: string;
                name: string;
            };
            /** Format: uuid */
            targetObjectId: string;
            prechangeState: {
                [key: string]: unknown;
            } | null;
            postchangeState: {
                [key: string]: unknown;
            } | null;
        };
        GetAuditLogsResponse: {
            data: components["schemas"]["AuditLog"][];
        };
    };
    responses: {
        /** @description General Error */
        "default-error": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorContent"];
            };
        };
        /** @description Unauthorized */
        "default-unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorContent"];
            };
        };
        /** @description Conflict, resource duplication */
        "default-conflict": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorContent"];
            };
        };
        /** @description Forbidden */
        "default-forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorContent"];
            };
        };
        /** @description Auth response */
        AuthResponse: {
            headers: {
                "Set-Cookie": string;
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Bad Request */
        "default-bad-request": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorContent"];
            };
        };
        /** @description Logout response */
        LogoutResponse: {
            headers: {
                "Set-Cookie": string;
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationsResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            default: components["responses"]["default-error"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrganizationResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            409: components["responses"]["default-conflict"];
            default: components["responses"]["default-error"];
        };
    };
    getOrganizationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationByIdResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getOrganizationUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationUnitsResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    createUnit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrganizationUnitResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getOrganizationUnitById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationUnitByIdResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    updateOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationUnitResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    deleteOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    patchOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchOrganizationUnitResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getStorageGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStorageGroupsResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    createStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorageGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateStorageGroupResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getStorageGroupById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStorageGroupByIdResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    updateStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStorageGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStorageGroupResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    deleteStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    patchStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchStorageGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchStorageGroupResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getCellsGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCellsGroupsResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    createCellsGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCellsGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCellsGroupResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getCellsGroupById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cells Group ID */
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCellsGroupByIdResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    updateCellsGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cells Group ID */
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCellsGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCellsGroupResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    deleteCellsGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cells Group ID */
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    patchCellsGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cells Group ID */
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchCellsGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchCellsGroupResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getCells: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCellsResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    createCell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCellRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCellResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getCellById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                cellId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCellByIdResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    updateCell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                cellId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCellRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCellResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    deleteCell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                cellId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["default-error"];
        };
    };
    patchCell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                cellId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchCellRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchCellResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetItemsResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateItemResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getItemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetItemByIdResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateItemResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["default-error"];
        };
    };
    patchItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchItemRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchItemResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInstancesResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getInstancesByItemId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInstancesByItemIdResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    createInstanceForItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstanceForItemRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInstanceForItemResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    deleteInstanceById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Instance ID */
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getApiTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApiTokensResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiTokenRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApiTokenResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    revokeApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    exchangeYandexAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Yandex Access token received from Yandex OAuth on Frontend */
                    access_token: string;
                };
            };
        };
        responses: {
            200: components["responses"]["AuthResponse"];
            400: components["responses"]["default-bad-request"];
            default: components["responses"]["default-error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["LogoutResponse"];
            401: components["responses"]["default-unauthorized"];
            default: components["responses"]["default-error"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCurrentUserResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            default: components["responses"]["default-error"];
        };
    };
    putCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCurrentUserRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCurrentUserResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            default: components["responses"]["default-error"];
        };
    };
    patchCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchCurrentUserRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCurrentUserResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            default: components["responses"]["default-error"];
        };
    };
    getEmployees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of employees */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetEmployeesResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getEmployeeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single employee */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetEmployeeResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    deleteEmployeeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    patchEmployeeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchEmployeeRequest"];
            };
        };
        responses: {
            /** @description A single employee */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetEmployeeResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    inviteEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteEmployeeRequest"];
            };
        };
        responses: {
            /** @description Employee invited successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetEmployeeResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
    getRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Role"][];
                    };
                };
            };
            401: components["responses"]["default-unauthorized"];
            default: components["responses"]["default-error"];
        };
    };
    getAuditLogs: {
        parameters: {
            query?: {
                /** @description The type of the object to filter by */
                object_type_id?: number;
                /** @description The id of the object to filter by */
                object_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAuditLogsResponse"];
                };
            };
            401: components["responses"]["default-unauthorized"];
            403: components["responses"]["default-forbidden"];
            default: components["responses"]["default-error"];
        };
    };
}
