/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Organizations */
        get: operations["getOrganizations"];
        put?: never;
        /** Create Organization */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Organization by ID */
        get: operations["getOrganizationById"];
        /** Update Organization */
        put: operations["updateOrganization"];
        post?: never;
        /** Delete Organization */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        /** Update Organization */
        patch: operations["patchOrganization"];
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Organization Units */
        get: operations["getOrganizationUnits"];
        put?: never;
        /** Create Organization Unit */
        post: operations["createUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Unit by ID */
        get: operations["getOrganizationUnitById"];
        /** Update Organization Unit */
        put: operations["updateOrganizationUnit"];
        post?: never;
        /** Delete Organization Unit */
        delete: operations["deleteOrganizationUnit"];
        options?: never;
        head?: never;
        /** Patch Organization Unit */
        patch: operations["patchOrganizationUnit"];
        trace?: never;
    };
    "/storage-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Storage Groups */
        get: operations["getStorageGroups"];
        put?: never;
        /** Create Storage Group */
        post: operations["createStorageGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Storage Group by ID */
        get: operations["getStorageGroupById"];
        /** Update Storage Group */
        put: operations["updateStorageGroup"];
        post?: never;
        /** Delete Storage Group */
        delete: operations["deleteStorageGroup"];
        options?: never;
        head?: never;
        /** Patch Storage Group */
        patch: operations["patchStorageGroup"];
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Items */
        get: operations["getItems"];
        put?: never;
        /** Create Item */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Item by ID */
        get: operations["getItemById"];
        /** Update Item */
        put: operations["updateItem"];
        post?: never;
        /** Delete Item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        /** Patch Item */
        patch: operations["patchItem"];
        trace?: never;
    };
    "/auth/oauth2/yandex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Yandex Access token for Session token */
        post: operations["exchangeYandexAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/testing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Auth Cookie by email */
        post: operations["getAuthCookieByEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Represents error object */
        Error: {
            error_id: string;
            message: string;
        };
        OrganizationBase: {
            /** @example Exotic */
            name: string;
            /** @example exotic */
            subdomain: string;
        };
        Organization: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            readonly id: string;
        } & components["schemas"]["OrganizationBase"];
        GetOrganizationsResponse: {
            data: components["schemas"]["Organization"][];
        };
        CreateOrganizationRequest: components["schemas"]["OrganizationBase"];
        CreateOrganizationResponse: {
            data: components["schemas"]["Organization"];
        };
        GetOrganizationByIdResponse: {
            data: components["schemas"]["Organization"];
        };
        UpdateOrganizationRequest: components["schemas"]["Organization"];
        UpdateOrganizationResponse: {
            data: components["schemas"]["Organization"][];
        };
        OrganizationPatch: {
            /** @example Exotic */
            name?: string;
            /** @example exotic */
            subdomain?: string;
        };
        PatchOrganizationRequest: components["schemas"]["OrganizationPatch"];
        PatchOrganizationResponse: {
            data?: components["schemas"]["Organization"][];
        };
        UnitBase: {
            /** @example Moscow */
            name: string;
            /** @example MWS */
            alias: string;
            /** @example 123 Main St, Moscow, Russia */
            address?: string | null;
        };
        Unit: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            readonly id: string;
        } & components["schemas"]["UnitBase"] & {
            address: string | null;
        };
        GetOrganizationUnitsResponse: {
            data: components["schemas"]["Unit"][];
        };
        CreateOrganizationUnitRequest: components["schemas"]["UnitBase"];
        CreateOrganizationUnitResponse: {
            data: components["schemas"]["Unit"];
        };
        GetOrganizationUnitByIdResponse: {
            data: components["schemas"]["Unit"];
        };
        UpdateOrganizationUnitRequest: components["schemas"]["UnitBase"];
        UpdateOrganizationUnitResponse: {
            data: components["schemas"]["Unit"][];
        };
        UnitPatch: {
            /** @example Moscow */
            name?: string;
            /** @example MWS */
            alias?: string;
            address?: string | null;
        };
        PatchOrganizationUnitRequest: components["schemas"]["UnitPatch"];
        PatchOrganizationUnitResponse: {
            data: components["schemas"]["Unit"][];
        };
        StorageGroupBase: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            parentId?: string | null;
            /** @example Main Warehouse */
            name: string;
            /** @example MW */
            alias: string;
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            unitId: string;
        };
        StorageGroup: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            readonly id: string;
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            parentId: string | null;
        } & components["schemas"]["StorageGroupBase"];
        GetStorageGroupsResponse: {
            data: components["schemas"]["StorageGroup"][];
        };
        CreateStorageGroupRequest: components["schemas"]["StorageGroupBase"];
        CreateStorageGroupResponse: {
            data: components["schemas"]["StorageGroup"];
        };
        GetStorageGroupByIdResponse: {
            data: components["schemas"]["StorageGroup"];
        };
        UpdateStorageGroupRequest: components["schemas"]["StorageGroupBase"];
        UpdateStorageGroupResponse: {
            data: components["schemas"]["StorageGroup"][];
        };
        StorageGroupPatch: {
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            parentId?: string | null;
            /** @example Main Warehouse */
            name?: string;
            /** @example MW */
            alias?: string;
            /**
             * Format: uuid
             * @example def3df1a-7b8f-4552-b437-a1eab851403f
             */
            unitId?: string;
        };
        PatchStorageGroupRequest: components["schemas"]["StorageGroupPatch"];
        PatchStorageGroupResponse: {
            data: components["schemas"]["StorageGroup"][];
        };
        ItemBase: {
            /** Format: uuid */
            readonly id?: string;
            /** @example Item 1 */
            name: string;
            /** @example Description */
            description?: string | null;
        };
        Item: components["schemas"]["ItemBase"] & {
            /** Format: uuid */
            readonly id: string;
            description: string | null;
        };
        GetItemsResponse: {
            data: components["schemas"]["Item"][];
        };
        ItemVariantBase: {
            /** @example Variant 1 */
            name: string;
            /** @example 123456789012 */
            article?: string | null;
            /** @example 1234567890123 */
            ean13?: number | null;
        };
        ItemCreate: components["schemas"]["ItemBase"] & {
            variants: components["schemas"]["ItemVariantBase"][];
        };
        CreateItemRequest: components["schemas"]["ItemCreate"];
        ItemVariant: {
            /** Format: uuid */
            readonly id: string;
        } & components["schemas"]["ItemVariantBase"] & {
            /** @example 123456789012 */
            article: string | null;
            /** @example 1234567890123 */
            ean13: number | null;
        };
        ItemFull: components["schemas"]["Item"] & {
            variants: components["schemas"]["ItemVariant"][];
        };
        CreateItemResponse: {
            data: components["schemas"]["ItemFull"];
        };
        GetItemByIdResponse: {
            data: components["schemas"]["ItemFull"];
        };
        ItemVariantEdit: {
            /** Format: uuid */
            id: string;
        } & components["schemas"]["ItemVariantBase"];
        UpdateItemRequest: components["schemas"]["ItemCreate"] & {
            variants: components["schemas"]["ItemVariantEdit"][];
        };
        UpdateItemResponse: {
            data: components["schemas"]["ItemFull"];
        };
        ItemVariantPatchInItem: {
            /** Format: uuid */
            id?: string;
            /** @example Variant 1 */
            name?: string;
            /** @example 123456789012 */
            article?: string | null;
            /** @example 1234567890123 */
            ean13?: number | null;
        };
        ItemPatch: {
            /** @example Item 1 */
            name?: string;
            /** @example Description */
            description?: string | null;
            variants?: components["schemas"]["ItemVariantPatchInItem"][];
        };
        PatchItemRequest: components["schemas"]["ItemPatch"];
        PatchItemResponse: {
            data: components["schemas"]["ItemFull"];
        };
        GetAuthCookieByEmailRequest: {
            /** Format: email */
            email: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            middle_name: string | null;
            email: string;
        };
        GetCurrentUserResponse: components["schemas"]["User"];
    };
    responses: {
        /** @description General Error */
        "default-error": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Auth response */
        AuthResponse: {
            headers: {
                "Set-Cookie": string;
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationsResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrganizationResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getOrganizationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationByIdResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["default-error"];
        };
    };
    patchOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchOrganizationResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getOrganizationUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationUnitsResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    createUnit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrganizationUnitResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getOrganizationUnitById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrganizationUnitByIdResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    updateOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationUnitResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    deleteOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["default-error"];
        };
    };
    patchOrganizationUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchOrganizationUnitResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getStorageGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStorageGroupsResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    createStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorageGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateStorageGroupResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getStorageGroupById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStorageGroupByIdResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    updateStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStorageGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStorageGroupResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    deleteStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["default-error"];
        };
    };
    patchStorageGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage Group ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchStorageGroupRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchStorageGroupResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetItemsResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateItemResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    getItemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetItemByIdResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateItemResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["default-error"];
        };
    };
    patchItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchItemRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchItemResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
    exchangeYandexAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Yandex Access token */
                    access_token: string;
                };
            };
        };
        responses: {
            200: components["responses"]["AuthResponse"];
            default: components["responses"]["default-error"];
        };
    };
    getAuthCookieByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetAuthCookieByEmailRequest"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["default-error"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCurrentUserResponse"];
                };
            };
            default: components["responses"]["default-error"];
        };
    };
}
